package leetcode;

/**
 * 392. Is Subsequence
 * <p>
 * Given two strings s and t, return true if s is a subsequence of t, or false otherwise. A
 * subsequence of a string is a new string generated by deleting some (can be none) of the
 * characters without changing the relative order of the remaining characters. For example, "ace" is
 * a subsequence of "abcde" while "aec" is not.
 * <p>
 * Example 1: Input: s = "abc", t = "ahbgdc" Output: true
 * <p>
 * Example 2: Input: s = "axc", t = "ahbgdc" Output: false
 * <p>
 * Constraints: - 0 <= s.length <= 100 - 0 <= t.length <= 10^4 - s and t consist only of lowercase
 * English letters.
 */
public class IsSubsequence {


  public boolean isSubsequence(String s, String t) {
    int i = 0, j = 0;

    while (i < s.length() && j < t.length()) {
      if (s.charAt(i) == t.charAt(j)) {
        i++;
      }
      j++;
    }

    return i == s.length();
  }
}
